title: Nick Milliken # your name (or website title) here
logo: "Head Shot from Family Shoot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate of the University of Colorado Boulder with a Master of Science Busness Analytics Degree (Security Track) Degree. 
  <br><br>
  Owner/Consultant at The Art of Life Academy LLC
  <br><br>
  Using empirical data to help people find their best path forward.
  <br><br>
  <a href="Nick Milliken - Resume.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/nick-milliken">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://vqmartialarts.com">View the VQ website</a>

theme: jekyll-theme-minimal 


google_analytics: UA-000000-0 # your Google Analytics tracking ID here
